version: "3.1"

services:

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flixtie-portal
    volumes:
      - ./flixtie-portal/:/var/www/html
      - ./virtualhost.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "80:80"
    links:
      - memcached:memcached

  memcached:
    image: memcached
    ports:
      - "11211:11211"